[theme]
base="light"
primaryColor = "#88379C"
showSidebarBorder = false

[theme.sidebar]
baseRadius = "none"

[server]
runOnSave = true

[runner]
enforceSerializableSessionState = true


